### ISSUE TITLE
Naming PMML and Lime files. 

### ISSUE THREAD

**Issue by DougManuel** [OHRImHealth/predictive-algorithms#2]
Yulric, 
Can you suggest a naming convention for the PMML and Lime files. I think in your code you are currently referencing 'algorithm.xml'?? Is this name what your were thinking, or did you want the algorithm name in the file name? something like MPoRTvX.xml

**Comment by yulric** [comment]
I'm fine with any name format. If possible, I would prefer underscores to be used instead of spaces.

**Comment by DougManuel** [comment]
What about: algorithm name_version_pmml.xls or .json
i.e. MPORT_0.0.1_pmml.xls 
would you then parse to: MPORT_0.0.1_PMML.json

Doug

**Comment by yulric** [comment]
Yeah, that works
