### ISSUE TITLE
Name conventions for Optype= RCS, interaction and categorical variables

### ISSUE THREAD

**Issue by DougManuel** [OHRImHealth/predictive-algorithms#5]
Note that all the optypes are "continuous". It is going to take a bit of time modify these terms during PMML production in R, but we will get there sooner or later.

However, Meltem has done a nice job of already adding suffixes to the predictor names to identify what type of variable they are. For example, she has used the suffix _rcs to identify variables that are restrictive cubic splines. 

I've cleaned these up just a bit (cleaning finished in  commit [https://github.com/OHRImHealth/predictive-algorithms/commit/31ccb9d531c432adc8ee8c88cbff84370f16e0f6] 

**Will this work?** 
We use just the name to identify the optype. 
**1)** name_rcs identifies name as optype = restrictive cubic spline. rcsc = constant, rcs1 = knot#1, rcs2 = knot#2, etc. 
**2)** name_int identifies name as optype = interaction. Within the name, there are the interaction terms.
**3)** continuous variables. We could add a suffix _cont or leave this as the default if there is not recognized suffix. 
**4)** categorical variables. We probably want to add a suffix of _cat. However, all our current categorical variables are 0 or 1. This may be the case for the future as well. This means that we could keep the optype as continuous since the returned value should always be correct -- because the beta will only be multiplied by 0 or 1 depending on the response. The allowable response values are (or should be) reflected and defined in Lime.

I still see a few issues in the naming convention in the current code, such as the use of '_' in places other than suffix. The use of '_' other than optype naming maybe bug prone for cat ownership predictors, etc. "has_cat_rcs"(both _cat and _rcs suffix). What I suggest is you make any further changes to that XML file to reflect what you think is the best naming convention. We can then flow that back to Meltem and the other analysts to incorporate into the next creation of the PMML file. 

There are one of two small issues that I see with variable names. i.e. interaction term for diet3 but no "base" term. Tell me if you notice anything and I can flow that back to Meltem along with any other name changes we need. 

Finally, you'll notice that the xml file is a few thousand lines long! Don't worry about that at this point. We don't really need those extra lines 'time' variables for most applications of the algorithm, but they may be nice for the end-of-life algorithms coming down the line. Those 'time' variables reflect how the baseline risk changes over time. They allow the risk function to calculate risk for any time period - from 0 to 12 years in this algorithm. Typically, we calculate risk for only a few time periods, usually 5 year risk, so those baseline risks can be whittled down to only a few lines.

**Comment by DougManuel** [comment]
Resolved -- for now.
1) Camel case for predictive variables. 
2) _suffix for OpType.
3) Continue to add OpType.

**Comment by vruusmann** [comment]
I've been using the following convention for naming derived fields: `func(arg)` (instead of `arg_func`). It's more readable for those that have some background in computer programming, and allows for easy extensions (eg. multiple arguments `func(arg1, arg2)`, nested function calls `func2(func1(arg))`) and parseability.

So, your knot#1 could be named `rcs1(field)` instead.

**Comment by DougManuel** [comment]
Villu, Thanks for taking the time to post. We will definitely consider.

**Comment by DougManuel** [comment]
Villu,
We would like to have our naming conventions the same what we use during algorithm development -- using R and SAS. Parenthesis are not a valid character for naming arguments. Any thoughts?
